version: "3"

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - selenium-hub
    environment:
      - FLASK_APP=http_app.py
      - FLASK_ENV=development
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"
    stdin_open: true
    command: bash -c "flask run --host 0.0.0.0"

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome-debug
    stdin_open: true
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
