version: "3"

services:
  test-app:
    build:
      context: .
      dockerfile: functional_tests/Dockerfile
    volumes:
      - ./functional_tests:/src
    links:
      - selenium-hub
    stdin_open: true

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome-debug
    stdin_open: true
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
