version: "3"

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - FLASK_APP=http_app.py
      - FLASK_ENV=development
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"
    stdin_open: true
    command: bash -c "flask run --host 0.0.0.0"
